# spring's autoconfiguration runs here (use # to comment out).
# .properties formate is key = value.
spring.data.mongodb.host=localhost    
 #  loacalhost  is a host name,its a loopback ip address only u onthat machine caan connect to it ip meaans internet protocol.
spring.data.mongodb.port=27017
spring.data.mongodb.database=test
# now here index will create autonmatically keep in mind this auto-index-creation is only for user entity
# this further line is property of spring data mongodb.
spring.data.mongodb.auto-index-creation=true 


#here no username and passwword but in case if it exist then use
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword
# so by using this formate your spring boot application made connection with mongodb.



/